# Generated by Django 6.0 on 2025-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('area_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=9)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_status', models.CharField(max_length=50)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
